name: publish-pull-request
run-name: ${{ github.actor }} is publishing a pull request
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build dist
        run: |
          npm install
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: /dist

  release:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Get PR Tag name
        id: pr_tagname
        run: |
          git fetch --prune --all --depth=500
          git checkout --track origin/main
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          COMMIT=$(git rev-parse --short HEAD)
          echo "tagname=${LATEST_TAG}-${COMMIT}" >> $GITHUB_OUTPUT
          git checkout "${{ steps.extract_branch.outputs.branch }}"
    outputs:
      tagname: ${{ steps.pr_tagname.outputs.tagname }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - compile
      - release
    steps:
      - name: Set tagname
        id: set_tagname
        run: echo "release_name=yjc-schools-map-${{needs.release.outputs.tagname}}" >> $GITHUB_ENV

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: ${{env.release_name}}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.release_name}}
          path: ${{ runner.temp }}/${{env.release_name}}.tar
          retention-days: 5
          if-no-files-found: error
