name: publish
run-name: ${{ github.actor }} is publishing a new version
on:
  push:
    branches:
      - master
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run:
  release:
    runs-on: ubuntu-latest
    steps:
